#!/bin/bash

SRC_ASM="../../../examples/example3.uav.asm"
SRC_BIN="../../../examples/example3.uav.bin"

echo "Displaying mission..."
cat $SRC_ASM
echo ""

echo "Generating binary code..."
java -cp java/classes/:java/lib/antlr-3.2.jar flipsCompiler $SRC_ASM
echo ""

echo "Running mission..."
./flips $SRC_BIN

